// food-swipe-mobile/src/common/components/ui/form/input.tsx
import { JSX, ParentComponent, Show, splitProps } from "solid-js";

type Props = JSX.InputHTMLAttributes<HTMLInputElement>;

export const Input: ParentComponent<Props> = (props) => {
  const iconPrefix = false;
  const [, inputProps] = splitProps(props, ["value"]);
  return (
    <label>
      <p>{props.children}</p>
      <div class="flex rounded border border-gray-300 px-1.5 py-1 outline-0 transition-colors invalid:border-danger-600 focus-within:border-primary-500 disabled:bg-gray-200 dark:border-dark-700 dark:bg-dark-800">
        <div class="grow">
          <input
            {...inputProps}
            value={props.value}
            class="w-full bg-transparent outline-none"
          />
        </div>
        <Show when={iconPrefix}>
          <div class="px-2">
            {/* <fa-icon [icon]="iconSuffix"></fa-icon> */}
          </div>
        </Show>
      </div>
    </label>
  );
};

// apps/food-swipe-admin-vue/src/components/ui/form/input.vue
<script setup lang="ts">
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

type InputType = 'number' | 'text' | 'email' | 'password' | 'file'

const { placeholder, disabled, type, iconSuffix } = defineProps<{
  placeholder?: string
  disabled?: boolean
  type?: InputType
  iconSuffix?: IconDefinition
}>()

const model = defineModel<string | number>()
</script>

<template>
  <label>
    <p><slot /></p>
    <div
      class="invalid:border-danger-600 focus-within:border-primary-600 flex rounded-sm border border-gray-200 px-1.5 py-1 outline-0 transition-colors disabled:bg-gray-200"
    >
      <div class="grow">
        <input
          v-model="model"
          :placeholder="placeholder"
          :disabled="disabled"
          :type="type"
          class="w-full bg-transparent outline-hidden"
        />
      </div>
      <div v-if="iconSuffix" class="px-2 text-gray-500">
        <FontAwesomeIcon :icon="iconSuffix" />
      </div>
    </div>
  </label>
</template>

<style scoped></style>
