// food-swipe-admin-vue/src/views/recipes/recipe.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Recipe } from '@/modules/recipe/types/recipe.type'
import Button from '@/components/ui/button.vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faQuestion, faSpinner } from '@fortawesome/free-solid-svg-icons'
import Input from '@/components/ui/form/input.vue'

// @ts-ignore
const recipe = ref<Recipe>({})
const loading = ref(false)

function deleteRecipe(id: number) {
  console.log('deleteRecipe', id)
}

function openFileUploader() {
  console.log('openFileUploader')
}

function uploadFile(event: Event) {
  console.log('uploadFile', event)
}

function updateRecipe(key: string, event: Event) {
  console.log('updateRecipe', key, event)
}
</script>

<template v-if="recipe">
  <div class="flex justify-end">
    <Button @click="deleteRecipe(recipe.id)" color="danger">Delete</Button>
  </div>
  <div class="flex">
    <div class="w-1/3">
      <div @click="openFileUploader()">
        <div
          v-if="loading"
          class="flex aspect-video w-full cursor-pointer items-center justify-center"
        >
          <FontAwesomeIcon size="10x" spin :icon="faSpinner" />
        </div>
        <div v-else-if="recipe.coverImageUrl" class="cursor-pointer">
          <img :src="recipe.coverImageUrl" alt="" />
        </div>
        <div
          v-else
          class="flex aspect-video w-full cursor-pointer items-center justify-center bg-gray-100"
        >
          <FontAwesomeIcon size="10x" :icon="faQuestion" />
        </div>
        <input type="file" hidden @change="uploadFile($event)" />
      </div>
      <div class="mt-4 flex gap-2">
        <div>
          <Input
            type="number"
            :value="recipe.calories?.toString() ?? ''"
            @blur="updateRecipe('calories', $event)"
            >Cals</Input
          >
        </div>
        <div>
          <Input
            type="number"
            :value="recipe.prepTime?.toString() ?? ''"
            @blur="updateRecipe('prepTime', $event)"
            >Time</Input
          >
        </div>
        <div>
          <Input
            type="number"
            :value="recipe.servings?.toString() ?? ''"
            @blur="updateRecipe('servings', $event)"
            >serv</Input
          >
        </div>
      </div>
    </div>
    <div class="w-2/3 p-8 pt-0">
      <h1 class="font-bold">
        <Input :value="recipe.title" @blur="updateRecipe('title', $event)">
          <span class="font-normal">Title</span>
        </Input>
      </h1>
      <p class="mt-1 text-gray-600">
        <!--        <app-form-textarea-->
        <!--          autoSize-->
        <!--          [value]="recipe.description"-->
        <!--          @blur="updateRecipe('description', $event)"-->
        <!--          >Description</app-form-textarea>-->
      </p>
      <div>
        <!--        <app-form-checkbox [value]="recipe.isPublished" (change)="updateIsPublished($event)"-->
        <!--          >Is publish</app-form-checkbox>-->
      </div>
    </div>
  </div>

  <div class="mt-8">
    <!--    <div class="mb-1 flex gap-2">-->
    <!--      <h2 class="grow text-2xl font-bold">Ingredients</h2>-->
    <!--      <app-button size="small" (click)="openManageIngredientDialog(recipe.id)"-->
    <!--      >Add ingredient</app-button-->
    <!--      >-->
    <!--    </div>-->
    <!--    <div class="table-container">-->
    <!--      <div class="ingredients">-->
    <!--        <div class="t-row ingredient">-->
    <!--          <div class="name">Ingredient</div>-->
    <!--          <div class="amount min-w-20 flex-shrink">Amount</div>-->
    <!--          <div class="min-w-28 flex-shrink"></div>-->
    <!--        </div>-->
    <!--        @for (ingredient of ingredients(); track ingredient) {-->
    <!--        <div class="t-row flex items-center">-->
    <!--          <div class="name">{{ ingredient.ingredient }}</div>-->
    <!--          <div class="amount min-w-20 flex-shrink">-->
    <!--            {{ ingredient.amount }}{{ ingredient.measurement }}-->
    <!--          </div>-->
    <!--          <div class="flex min-w-28 flex-shrink gap-1">-->
    <!--            <app-button-->
    <!--              type="icon"-->
    <!--              size="small"-->
    <!--              (click)="-->
    <!--                  openManageIngredientDialog(recipe.id, ingredient.ingredientId)-->
    <!--                "-->
    <!--            ><fa-icon [icon]="faPencil"-->
    <!--            /></app-button>-->
    <!--            <app-button-->
    <!--              type="icon"-->
    <!--              size="small"-->
    <!--              color="danger"-->
    <!--              (click)="deleteIngredient(ingredient.ingredientId)"-->
    <!--            ><fa-icon [icon]="faTrash"-->
    <!--            /></app-button>-->
    <!--          </div>-->
    <!--        </div>-->
    <!--        }-->
    <!--      </div>-->
    <!--    </div>-->
  </div>

  <div class="mt-8">
    <!--    <div class="mb-1 flex gap-2">-->
    <!--      <h2 class="grow text-2xl font-bold">Steps</h2>-->
    <!--      <app-button size="small" (click)="openManageStepDialog(recipe.id)"-->
    <!--      >Add Step</app-button-->
    <!--      >-->
    <!--    </div>-->
    <!--    <div class="table-container">-->
    <!--      <div-->
    <!--        class="ingredients"-->
    <!--        cdkDropList-->
    <!--        (cdkDropListDropped)="stepsDrop($event)"-->
    <!--      >-->
    <!--        <div class="t-row ingredient">-->
    <!--          <div class="step min-w-20 flex-shrink">Step</div>-->
    <!--          <div class="description">Description</div>-->
    <!--          <div class="min-w-28 flex-shrink"></div>-->
    <!--        </div>-->
    <!--        @for (step of steps(); track step.id) {-->
    <!--        <div class="t-row flex items-center" cdkDrag>-->
    <!--          <div class="step min-w-20 flex-shrink">{{ step.stepNumber }}</div>-->
    <!--          <div class="description">{{ step.description }}</div>-->
    <!--          <div class="flex min-w-28 flex-shrink gap-1">-->
    <!--            <app-button-->
    <!--              type="icon"-->
    <!--              size="small"-->
    <!--              (click)="openManageStepDialog(recipe.id, step.id)"-->
    <!--            ><fa-icon [icon]="faPencil"-->
    <!--            /></app-button>-->
    <!--            <app-button-->
    <!--              type="icon"-->
    <!--              size="small"-->
    <!--              color="danger"-->
    <!--              (click)="deleteStep(step.id)"-->
    <!--            ><fa-icon [icon]="faTrash"-->
    <!--            /></app-button>-->
    <!--          </div>-->
    <!--        </div>-->
    <!--        }-->
    <!--      </div>-->
    <!--    </div>-->
  </div>
</template>

<style scoped></style>

// apps/food-swipe-admin/src/app/pages/recipes/recipe/recipe.component.ts
import {
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  numberAttribute,
  signal,
  viewChild,
} from '@angular/core';
import { RecipeRepository } from '@modules/recipes/recipe.repository';
import { CdkDrag, CdkDragDrop, CdkDropList } from '@angular/cdk/drag-drop';
import { ButtonComponent } from '../../../common/components/ui/button/button.component';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';
import {
  faPencil,
  faQuestion,
  faSpinner,
  faTrash,
} from '@fortawesome/free-solid-svg-icons';
import { ManageRecipeStepDialogComponent } from '@modules/recipes/components/manage-recipe-step-dialog/manage-recipe-step-dialog.component';
import { Dialog } from '@angular/cdk/dialog';
import { ManageRecipeIngredientDialogComponent } from '@modules/recipes/components/manage-recipe-ingredient-dialog/manage-recipe-ingredient-dialog.component';
import { FormInputComponent } from '../../../common/components/ui/form/form-input/form-input.component';
import { FormsModule } from '@angular/forms';
import { FormTextareaComponent } from '../../../common/components/ui/form/form-textarea/form-textarea.component';
import { Recipe } from '@modules/recipes/types/recipe.type';
import { FormCheckboxComponent } from '../../../common/components/ui/form/form-checkbox/form-checkbox.component';
import { Router } from '@angular/router';
import {
  Nutrition,
  nutritionOrder,
  nutritions,
  NutritionUnit,
  nutritionUnits,
} from '@modules/recipes/constants/nutritions';
import { RecipeNutrition } from '@modules/recipes/types/recipe-nutrition.type';
import { FormSelectComponent } from '../../../common/components/ui/form/form-select/form-select.component';

@Component({
  selector: 'app-recipe',
  imports: [
    CdkDropList,
    CdkDrag,
    ButtonComponent,
    FaIconComponent,
    FormInputComponent,
    FormsModule,
    FormTextareaComponent,
    FormCheckboxComponent,
    FormSelectComponent,
  ],
  templateUrl: './recipe.component.html',
  styleUrl: './recipe.component.scss',
})
export default class RecipeComponent {
  private readonly recipeRepository = inject(RecipeRepository);
  private readonly dialog = inject(Dialog);
  private readonly router = inject(Router);

  fileUploader =
    viewChild.required<ElementRef<HTMLInputElement>>('fileUploader');

  ingredients = this.recipeRepository.ingredients;
  steps = this.recipeRepository.steps;
  nutritions = computed(() => {
    const recipeId = this.id();
    const nutritions = this.recipeRepository.nutritions();
    const nutritionMap = new Map<string, RecipeNutrition>();
    for (const nutrition of nutritions) {
      nutritionMap.set(nutrition.name, nutrition);
    }
    const orderedNutritions: RecipeNutrition[] = [];
    for (const name of nutritionOrder) {
      const nutrition = nutritionMap.get(name);
      if (nutrition) {
        orderedNutritions.push(nutrition);
      } else {
        orderedNutritions.push({
          id: -1,
          recipeId,
          name,
          value: 0,
          unit: 'g',
        });
      }
    }
    return orderedNutritions;
  });

  id = input.required<number, string>({ transform: numberAttribute });
  recipe = computed(() => this.recipeRepository.getRecipe(this.id())());
  title = computed(() => this.recipe().title);
  description = computed(() => this.recipe().description);

  isLoading = this.recipeRepository.isLoading;
  isDeleting = false;
  isChangingImage = signal(false);

  protected readonly faTrash = faTrash;
  protected readonly faPencil = faPencil;

  constructor() {
    effect(() => {
      this.recipeRepository.loadRecipe(this.id());
      this.recipeRepository.loadSteps(this.id());
      this.recipeRepository.loadIngredients(this.id());
      this.recipeRepository.loadNutritions(this.id());
    });

    effect(() => {
      const isLoading = this.isLoading();
      if (this.isDeleting && !isLoading) {
        this.router.navigate(['/recipes']);
      }
    });

    effect(() => {
      const isLoading = this.isLoading();
      if (this.isChangingImage() && !isLoading) {
        this.isChangingImage.set(false);
      }
    });
  }

  updateRecipe(prop: keyof Recipe, event: Event) {
    const target = event.target;
    if (
      !(target instanceof HTMLInputElement) &&
      !(target instanceof HTMLTextAreaElement)
    ) {
      return;
    }
    const value = target.value;
    if (!value?.trim()) {
      return;
    }
    if (this.recipe()[prop] == value) {
      return;
    }
    this.recipeRepository.updateRecipe(this.id(), { [prop]: value });
  }

  updateIsPublished(event: Event) {
    const target = event.target;
    if (!(target instanceof HTMLInputElement)) {
      return;
    }
    this.recipeRepository.updateRecipe(this.id(), {
      isPublished: target.checked,
    });
  }

  openManageIngredientDialog(recipeId: number, ingredientId?: number) {
    this.dialog.open(ManageRecipeIngredientDialogComponent, {
      data: { recipeId, ingredientId },
    });
  }

  stepsDrop(event: CdkDragDrop<number[]>) {
    const steps = [...this.steps()];
    const stepId = steps[event.previousIndex].id;
    this.recipeRepository.reorderSteps(this.id(), stepId, {
      orderFrom: event.previousIndex + 1,
      orderTo: event.currentIndex + 1,
    });
  }

  openManageStepDialog(recipeId: number, stepId?: number) {
    this.dialog.open(ManageRecipeStepDialogComponent, {
      data: { recipeId, stepId },
    });
  }

  deleteStep(stepId: number) {
    this.recipeRepository.deleteStep(this.id(), stepId);
  }

  deleteIngredient(ingredientId: number) {
    this.recipeRepository.deleteIngredient(this.id(), ingredientId);
  }

  openFileUploader() {
    this.fileUploader().nativeElement.click();
  }

  uploadFile(event: Event) {
    const target = event.target;
    if (!target || !(target instanceof HTMLInputElement)) {
      return;
    }
    const file = target.files?.[0];
    if (!file) {
      return;
    }
    this.recipeRepository.uploadImage(this.id(), file);
    this.isChangingImage.set(true);
  }

  deleteRecipe(recipeId: number) {
    this.recipeRepository.deleteRecipe(recipeId);
    this.isDeleting = true;
  }

  updateNutritionValue(name: Nutrition, unit: NutritionUnit, event: Event) {
    if (
      !(event instanceof FocusEvent) ||
      !(event.target instanceof HTMLInputElement)
    ) {
      return;
    }
    const value = event.target.value;
    this.updateNutrition(name, unit, Number(value));
  }

  updateNutrition(name: Nutrition, unit: NutritionUnit, value: number) {
    this.recipeRepository.updateNutrition(this.id(), name, {
      value: value,
      unit,
    });
  }

  protected readonly faQuestion = faQuestion;
  protected readonly faSpinner = faSpinner;
  protected readonly nutritionUnits = nutritionUnits;
}

@if (recipe(); as recipe) {
  <div class="flex justify-end">
    <app-button (click)="deleteRecipe(recipe.id)" color="danger"
      >Delete</app-button
    >
  </div>
  <div class="flex">
    <div class="w-1/3">
      <div (click)="openFileUploader()">
        @if (isChangingImage()) {
          <div
            class="flex aspect-video w-full cursor-pointer items-center justify-center"
          >
            <fa-icon size="10x" [icon]="faSpinner" animation="spin" />
          </div>
        } @else if (recipe.coverImageUrl) {
          <div class="cursor-pointer">
            <img [src]="recipe.coverImageUrl" alt="" />
          </div>
        } @else {
          <div
            class="flex aspect-video w-full cursor-pointer items-center justify-center bg-gray-100"
          >
            <fa-icon size="10x" [icon]="faQuestion" />
          </div>
        }
        <input type="file" hidden #fileUploader (change)="uploadFile($event)" />
      </div>
      <div class="mt-4 flex gap-2">
        <div>
          <app-form-input
            type="number"
            [value]="recipe.prepTime?.toString() ?? ''"
            (blur)="updateRecipe('prepTime', $event)"
            >Time</app-form-input
          >
        </div>
        <div>
          <app-form-input
            type="number"
            [value]="recipe.servings?.toString() ?? ''"
            (blur)="updateRecipe('servings', $event)"
            >servings</app-form-input
          >
        </div>
      </div>
    </div>
    <div class="w-2/3 p-8 pt-0">
      <h1 class="font-bold">
        <app-form-input [value]="title()" (blur)="updateRecipe('title', $event)"
          ><span class="font-normal">Title</span></app-form-input
        >
      </h1>
      <p class="mt-1 text-gray-600">
        <app-form-textarea
          autoSize
          [value]="recipe.description"
          (blur)="updateRecipe('description', $event)"
          >Description</app-form-textarea
        >
      </p>
      <div>
        <app-form-checkbox
          [value]="recipe.isPublished"
          (change)="updateIsPublished($event)"
          >Is publish</app-form-checkbox
        >
      </div>
    </div>
  </div>

  <div class="mt-8">
    <div class="mb-1 flex gap-2">
      <h2 class="grow text-2xl font-bold">Ingredients</h2>
      <app-button size="small" (click)="openManageIngredientDialog(recipe.id)"
        >Add ingredient</app-button
      >
    </div>
    <div class="table-container">
      <div class="ingredients">
        <div class="t-row ingredient">
          <div class="name">Ingredient</div>
          <div class="amount min-w-20 flex-shrink">Amount</div>
          <div class="min-w-28 flex-shrink"></div>
        </div>
        @for (ingredient of ingredients(); track ingredient) {
          <div class="t-row flex items-center">
            <div class="name">{{ ingredient.ingredient }}</div>
            <div class="amount min-w-20 flex-shrink">
              {{ ingredient.amount }}{{ ingredient.measurement }}
            </div>
            <div class="flex min-w-28 flex-shrink gap-1">
              <app-button
                type="icon"
                size="small"
                (click)="
                  openManageIngredientDialog(recipe.id, ingredient.ingredientId)
                "
                ><fa-icon [icon]="faPencil"
              /></app-button>
              <app-button
                type="icon"
                size="small"
                color="danger"
                (click)="deleteIngredient(ingredient.ingredientId)"
                ><fa-icon [icon]="faTrash"
              /></app-button>
            </div>
          </div>
        }
      </div>
    </div>
  </div>

  <div class="mt-8">
    <div class="mb-1 flex gap-2">
      <h2 class="grow text-2xl font-bold">Steps</h2>
      <app-button size="small" (click)="openManageStepDialog(recipe.id)"
        >Add Step</app-button
      >
    </div>
    <div class="table-container">
      <div
        class="ingredients"
        cdkDropList
        (cdkDropListDropped)="stepsDrop($event)"
      >
        <div class="t-row ingredient">
          <div class="step min-w-20 flex-shrink">Step</div>
          <div class="description">Description</div>
          <div class="min-w-28 flex-shrink"></div>
        </div>
        @for (step of steps(); track step.id) {
          <div class="t-row flex items-center" cdkDrag>
            <div class="step min-w-20 flex-shrink">{{ step.stepNumber }}</div>
            <div class="description">{{ step.description }}</div>
            <div class="flex min-w-28 flex-shrink gap-1">
              <app-button
                type="icon"
                size="small"
                (click)="openManageStepDialog(recipe.id, step.id)"
                ><fa-icon [icon]="faPencil"
              /></app-button>
              <app-button
                type="icon"
                size="small"
                color="danger"
                (click)="deleteStep(step.id)"
                ><fa-icon [icon]="faTrash"
              /></app-button>
            </div>
          </div>
        }
      </div>
    </div>
  </div>

  <div class="mt-8">
    <div class="mb-1 flex gap-2">
      <h2 class="grow text-2xl font-bold">Nutrition's</h2>
    </div>
    <div class="table-container">
      <table class="table w-full">
        <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Unit</th>
          </tr>
        </thead>
        <tbody>
          @for (nutrition of nutritions(); track nutrition) {
            <tr>
              <td>{{ nutrition?.name }}</td>
              <td>
                <app-form-input
                  [ngModel]="nutrition.value"
                  (blur)="
                    updateNutritionValue(nutrition.name, nutrition.unit, $event)
                  "
                />
              </td>
              <td>
                <app-form-select
                  [ngModel]="nutrition.unit"
                  (ngModelChange)="
                    updateNutrition(nutrition.name, $event, nutrition.value)
                  "
                >
                  @for (unit of nutritionUnits; track unit) {
                    <option value="{{ unit }}">{{ unit }}</option>
                  }
                </app-form-select>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>
}
