// apps/admin/src/app/routes/_layout/recipes/recipes.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/common/components/ui/button";
import { Input } from "@/common/components/ui/input";
import { Search, Plus, Import } from "lucide-react";
import { useNavigate } from "@tanstack/react-router";
import { recipeApi } from "@/modules/recipes/recipe.api";
import { useQuery } from "@tanstack/react-query";
import styles from "./recipes.module.css";

export const Route = createFileRoute("/_layout/recipes/recipes")({
  component: RouteComponent,
});

function RouteComponent() {
  const [search, setSearch] = useState("");
  const navigate = useNavigate();
  let { data: recipes = [] } = useQuery({
    queryKey: ["recipes"],
    queryFn: () => recipeApi.getAll(),
  });

  const openCreateRecipeDialog = () => {
    // TODO: Implement create recipe dialog
  };

  const openImportDialog = () => {
    // TODO: Implement import dialog
  };

  return (
    <div className="p-4">
      <div className="mb-4 flex justify-between">
        <div className="w-64">
          <Input
            placeholder="Search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full"
          />
        </div>
        <div className="flex gap-2">
          <Button onClick={openCreateRecipeDialog}>
            <Plus className="size-4" />
            Create
          </Button>
          <Button onClick={openImportDialog}>
            <Import className="size-4" />
            Import
          </Button>
        </div>
      </div>

      <div className={`${styles.content} gap-4`}>
        {recipes.map((recipe) => (
          <div
            key={recipe.id}
            className="cursor-pointer rounded border transition-transform hover:scale-105 hover:shadow bg-primary-foreground"
            onClick={() =>
              navigate({
                to: "/recipes/$recipeId",
                params: { recipeId: recipe.id.toString() },
              })
            }
          >
            {recipe.coverImageUrl ? (
              <div>
                <img
                  src={recipe.coverImageUrl}
                  width={5120}
                  height={1440}
                  alt="Recipe Image"
                  className="rounded-t"
                />
              </div>
            ) : (
              <div className="flex h-48 w-full cursor-pointer items-center justify-center bg-gray-100">
                <Search className="size-10 text-gray-400" />
              </div>
            )}
            <div className="p-2">
              <h3 className="font-bold">{recipe.title}</h3>
              <div className="description">
                <p className="line-clamp-2">{recipe.description}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// food-swipe-admin-vue/src/views/recipes/recipes.vue
<script setup lang="ts">
import Input from '@/components/ui/form/input.vue'
import { ref } from 'vue'
import Button from '@/components/ui/button.vue'
import { useRecipeStore } from '@/modules/recipe/recipe.store'

const store = useRecipeStore()

store.loadRecipes()

const search = ref('')
</script>

<template>
  <div class="mb-4 flex justify-between bg-white">
    <div class="w-64">
      <Input placeholder="Search" iconSuffix="faMagnifyingGlass" v-model="search" />
      <!--      <app-form-input placeholder="Search" [iconSuffix]="faMagnifyingGlass" [(ngModel)]="search" />-->
    </div>
    <div>
      <Button>Create</Button>
      <Button>Import</Button>
      <!--      <app-button (click)="openCreateRecipeDialog()">Create</app-button>-->
      <!--      <app-button (click)="openImportDialog()">import</app-button>-->
    </div>
  </div>
  <div class="content gap-4">
    <router-link
      v-for="recipe in store.recipes"
      :key="recipe.id"
      :to="`/${recipe.id}`"
      :id="`recipe-${recipe.id}`"
    >
      <div class="cursor-pointer rounded border transition-transform hover:scale-105 hover:shadow">
        <div v-if="recipe.coverImageUrl">
          <img
            :src="recipe.coverImageUrl"
            width="5120"
            height="1440"
            alt="Recipe Image"
            class="rounded-t"
          />
        </div>
        <div v-else class="flex w-full cursor-pointer items-center justify-center bg-gray-100">
          <!--        <fa-icon size="10x" [icon]="faQuestion" />-->
        </div>
        <div class="p-2">
          <h3 class="font-bold">{{ recipe.title }}</h3>
          <div class="description">
            <p class="line-clamp-2">
              {{ recipe.description }}
            </p>
          </div>
        </div>
      </div>
    </router-link>
  </div>
</template>

<style scoped>
.content {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
}
</style>
