// apps/admin/src/components/ui/input.tsx
import * as React from "react";
import { Input as InputPrimitive } from "@base-ui/react/input";

import { cn } from "@/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <InputPrimitive
      type={type}
      data-slot="input"
      className={cn(
        "h-9 w-full min-w-0 rounded-md border border-input bg-transparent px-2.5 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 md:text-sm dark:bg-input/30 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40",
        className
      )}
      {...props}
    />
  );
}

export { Input };

// food-swipe-admin-vue/src/components/ui/form/input.vue
<script setup lang="ts">
type InputType = 'number' | 'text' | 'email' | 'password' | 'file'

const { placeholder, disabled, type, iconSuffix } = defineProps<{
  placeholder?: string
  disabled?: boolean
  type?: InputType
  iconSuffix?: string
}>()

const model = defineModel<string | number>()
</script>

<template>
  <label>
    <p><slot /></p>
    <div
      class="invalid:border-danger-600 flex rounded border px-1.5 py-1 outline-0 transition-colors focus-within:border-primary-600 disabled:bg-gray-200"
    >
      <div class="grow">
        <input
          v-model="model"
          :placeholder="placeholder"
          :disabled="disabled"
          :type="type"
          class="w-full bg-transparent outline-none"
        />
      </div>
      <!--      @if (iconSuffix()) {-->
      <!--      <div class="px-2 text-gray-500">-->
      <!--        <fa-icon [icon]="iconSuffix()!"></fa-icon>-->
      <!--      </div>-->
      <!--      }-->
    </div>
  </label>
</template>

<style scoped></style>
