// food-swipe-admin/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { SidebarComponent } from '../../common/components/sidebar/sidebar.component';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [SidebarComponent, RouterOutlet],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export default class HomeComponent {}

<div class="flex h-screen flex-row">
  <div class="w-64 border-r-2 bg-gray-100"><app-sidebar /></div>
  <main class="grow overflow-auto p-6">
    <div class="rounded p-4"><router-outlet /></div>
  </main>
</div>

// apps/food-swipe-admin-vue/src/views/home.vue
<script setup lang="ts">
import Sidebar from '@/components/sidebar/sidebar.vue'
</script>

<template>
  <div class="flex h-screen flex-row">
    <div class="w-64 min-w-64 border-r-2 bg-gray-100">
      <Sidebar />
    </div>
    <main class="grow overflow-auto">
      <div class="p-6">
        <Suspense>
          <router-view />
          <template #fallback>
            <div>Loading...</div>
          </template>
        </Suspense>
      </div>
    </main>
  </div>
</template>

<style scoped></style>
